### ISSUE TITLE
Keep or remove`gh-pages` branch

### ISSUE THREAD

**Issue by mmmavis** [mozilla/nsf-challenge#28]
Hey @gvn ,

Since now we have Jenkins and S3 set up for staging: https://wirelesschallenge.mofostaging.net/ , should we keep the `gh-pages` branch? I think having the deployment code in the codebase doesn't hurt but having a`gh-pages` branch on a repo can be a bit confusing. People should check out the real staging instance instead and not `github.io`. What do you think? Oh and we probably should update the staging section on README.md as well.

/cc @ScottDowne

**Comment by ScottDowne** [comment]
Makes sense to me.

**Comment by gvn** [comment]
Yeah, you can get rid of `gh-pages` on this repo. I'd suggest keeping the staging script because you can use it to stage your own personal build on your own fork (eg: `npm run stage mmmavis`) if you want to stage a feature you're working on for non-dev review.

**Comment by hannahkane** [comment]
@ScottDowne - can this ticket be assigned to you?
