### ISSUE TITLE
Remove link to official rules for launch

### ISSUE THREAD

**Issue by mehan** [mozilla/nsf-challenge#29]
@ScottDowne We've decided to hold off on publishing the official rules on the site until the submission form goes live. Could you remove the "Rules and regulations" link from the footer for the time being? We'll want to re-add it eventually, once we swap out the events links for submission links. Thanks!

**Comment by mmmavis** [comment]
hey @mehan should we take that page down for now (`/rules-and-regulations` becomes a 404) or just remove link to it from site footer? I guess it's the latter, but I'd like to double check with you. 😉 


/cc @ScottDowne

**Comment by ScottDowne** [comment]
The initial change has landed, however, the page is still available, we just don't link to it.

If we want it gone gone, we can.

**Comment by mehan** [comment]
@mmmavis @ScottDowne That's totally fine--all we need is to have the link removed. I can put some placeholder text on the rules page (i.e. "official rules will be published once submissions are open") just in case someone manages to find it. Thanks all!

**Comment by ScottDowne** [comment]
Closing.
