### ISSUE TITLE
Add CSP meta tag

### ISSUE THREAD

**Issue by cadecairos** [mozilla/nsf-challenge#31]
We've been asked to add a Content Security Policy for the site. Unfortunately, Cloudfront and S3 don't let us add Headers to responses, so we're going to have to use a `<meta>` tag.

Here's what the tag should be:

```html
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; font-src https://code.cdn.mozilla.net; img-src 'self'; script-src 'self'">
```

This should be the **first** tag in the `<head>` section of every HTML file we generate.

**Comment by mmmavis** [comment]
@ScottDowne can u take this one? 😉

**Comment by ScottDowne** [comment]
Yup. I can get to it tomorrow.

**Comment by april** [comment]
Awesome, thanks much.  Note that the Observatory doesn't yet understand &lt;meta&gt; tags so don't panic if you get penalized for not having CSP.  It's an open bug:

https://github.com/mozilla/http-observatory/issues/105

**Comment by ScottDowne** [comment]
Live reload is causing issues with CSP. I'm working on a solution.

**Comment by ScottDowne** [comment]
It's also failing the data uris in the footer icons.

**Comment by cadecairos** [comment]
> It's also failing the data uris in the footer icons.

can we have these load over the network from the same domain?

**Comment by ScottDowne** [comment]
Is the goal of making those data uris to reduce http requests?

**Comment by cadecairos** [comment]
Reducing HTTP requests < disallowing inline data URIs

**Comment by mmmavis** [comment]
Isn't live loading just for dev though? we aren't using it on staging or production.

**Comment by mmmavis** [comment]
I guess we have to allow `data:` for `img-src` for the footer icons to show.

**Comment by mmmavis** [comment]
@cadecairos is the expert on this. Maybe we should've not encoded SVGs in `mofo-bootstrap` since it would raise some security concerns? /cc @alanmoo @gvn

**Comment by ScottDowne** [comment]
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-iN7wpJdxHlpujRppkOA8N0+Mzp0ZqZr3lCtxM00Y63c='), or a nonce ('nonce-...') is required to enable inline execution.

127.0.0.1/:1 Refused to load the image 'data:image/svg+xml,%3Csvg%20width%3D%2218px%22%20height%3D%2218px%22%20view…%3E%0A%20%20%20%20%20%20%20%20%3C/g%3E%0A%20%20%20%20%3C/g%3E%0A%3C/svg%3E' because it violates the following Content Security Policy directive: "img-src 'self'".

127.0.0.1/:1 Refused to load the image 'data:image/svg+xml,%3Csvg%20width%3D%2218px%22%20height%3D%2218px%22%20view…%3E%0A%20%20%20%20%20%20%20%20%3C/g%3E%0A%20%20%20%20%3C/g%3E%0A%3C/svg%3E' because it violates the following Content Security Policy directive: "img-src 'self'".

127.0.0.1/:1 Refused to load the image 'data:image/svg+xml,%3Csvg%20width%3D%2218px%22%20height%3D%2218px%22%20view…%3E%0A%20%20%20%20%20%20%20%20%3C/g%3E%0A%20%20%20%20%3C/g%3E%0A%3C/svg%3E' because it violates the following Content Security Policy directive: "img-src 'self'".

127.0.0.1/:1 Refused to load the image 'data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22…%3E%0A%20%20%20%20%20%20%20%20%3C/g%3E%0A%20%20%20%20%3C/g%3E%0A%3C/svg%3E' because it violates the following Content Security Policy directive: "img-src 'self'".

```

Here are the actual error logs, for reference.

**Comment by alanmoo** [comment]
Would it work if the images were base64 encoded instead?

**Comment by april** [comment]
`img-src data:` should be perfectly safe to use  :)

**Comment by april** [comment]
(it's `script-src data:`, `object-src data:` and to a lesser extent `style-src data:` that are more dangerous)

**Comment by ScottDowne** [comment]
Yeah, I just came to that conclusion too.

**Comment by ScottDowne** [comment]
@marumari Any thoughts on the script injected via live-server?

**Comment by april** [comment]
Is the live server inline script identical every time?

**Comment by ScottDowne** [comment]
Not sure. It's likely, but I cannot seem to find anything in their docs about overriding how it injects this nonsense.

https://www.npmjs.com/package/live-server

**Comment by april** [comment]
Okay, gimme a bit and I'll figure it out for you.  :)

**Comment by ScottDowne** [comment]
Closed in https://github.com/mozilla/nsf-challenge/pull/35
