### ISSUE TITLE
Page structure changes possibly causing anchor links to not link to the proper location visually

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/nsf-challenge#39]
This is super weird. I noticed it last night, and only did a full bisect this morning because it was bugging me.

Bisect pointed to https://github.com/mozilla/nsf-challenge/commit/a5a4b298b8a8dbb3c9ff91edc2a21e41891807e8

STR:

1. Go to https://wirelesschallenge.mofostaging.net/
2. Click details in the nav
3. Do a hard refresh (ctrl+F5 for FF on Linux) See here for how to do this on other systems: https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.WJ9kI9VOmis

expected: 
![nav-scroll-good](https://cloud.githubusercontent.com/assets/197334/22856730/99d657c2-f065-11e6-9927-439e7375c0c8.png)
Actual: 
![nav-scroll](https://cloud.githubusercontent.com/assets/197334/22856731/9f5ac87c-f065-11e6-9ee8-e6ff93cdc320.png)

I didn't worry about this, until I figured out the csp header caused it, which worries me more than the symptom itself. Are we doing something super weird with CSP, or just a ff bug?

@cadecairos or @marumari any thoughts?

**Comment by ScottDowne** [comment]
So, I may be wrong about the cause. It's something else. I don't understand yet, but if I go to master and remove the meta, problem persists. Might be multiple causes, and both need to be removed.

**Comment by ScottDowne** [comment]
I was wrong. Borked the bisect somehow. Seems to be caused by https://github.com/mozilla/nsf-challenge/commit/48a66f73ea3999a7fe1bdc32ceb50d9a228e0182

Ignore all talks about CSP, no way that caused anything like this. (Would have been super weird if it did)

**Comment by ScottDowne** [comment]
So after more debugging, I think this is caused by client side react. We're likely going to need to setup our own anchor scrolling of sorts...

**Comment by april** [comment]
I can't seem to replicate this particular bug on my own system, if that's any help.

**Comment by ScottDowne** [comment]
Yeah, this seems like a race condition, and I'm starting to get fairly inconsistent results, and it does some weird things. Hence why the bisect was so misleading.

Example, if I make the page width narrower, it seems to get away.

What I suspect is happening is after page load, we inject react client side, which changes page height, at the same time the browser starts to scroll to an anchor. Ideally (if we could we delay the browser scroll until after react is done, which isn't possible as we have no control over that, nor do we know when react is done. or go with server side react rendering, which is also not an option in the current build.)

I think client side react needs a rethink.

**Comment by april** [comment]
Okay, I'm going to unfollow this bug, but feel free to pull me back in if it somehow ends up being CSP related.  :)

**Comment by ScottDowne** [comment]
I ended up fixing this and landing it just now in https://github.com/mozilla/nsf-challenge/commit/b4085cc0fca39716eea4733da3ee901c35556aa6

This fix is a soft fix. I actually handle the position in which the next section is scrolled to half the page, so now it's no longer a problem if the page loads slightly in the wrong spot, because it has half a page in height buffer.
