### ISSUE TITLE
Add anchor links to challenge headers

### ISSUE THREAD

**Issue by mehan** [mozilla/nsf-challenge#40]
@ScottDowne The NSF wants to link to each challenge individually--could we maybe add anchor links to each of the challenge headers (see below)?

![screen shot 2017-02-14 at 8 18 09 am](https://cloud.githubusercontent.com/assets/1390212/22937752/59a75572-f28e-11e6-92ea-b9e7082d389c.png)

**Comment by ScottDowne** [comment]
@mmmavis and the plot thickens.

**Comment by ScottDowne** [comment]
@mmmavis so either we close this, or I build it into https://github.com/mozilla/nsf-challenge/pull/25

It'll rely on checks I make in the above pull request to work, similar to the accordion.

**Comment by ScottDowne** [comment]
Landed in https://github.com/mozilla/nsf-challenge/commit/b4085cc0fca39716eea4733da3ee901c35556aa6
