### ISSUE TITLE
More padding needed

### ISSUE THREAD

**Issue by mehan** [mozilla/nsf-challenge#45]
After adding all of the text to the "details" section (i.e. the text sections that are hidden behind the accordion sliders), I noticed that each of those sections could probably use some more 'padding-bottom', as seen here:

![screen shot 2017-02-15 at 9 53 00 pm](https://cloud.githubusercontent.com/assets/1390212/23009686/35edba42-f3cc-11e6-9990-bac78e7f330e.png)

**Comment by ScottDowne** [comment]
Agreed. Been meaning to clean this up.
