### ISSUE TITLE
Switching around of icons

### ISSUE THREAD

**Issue by mehan** [mozilla/nsf-challenge#46]
The NSF folks wanted to move around some of the bullet points under the judging criteria. We'll probably want to switch around these icons so that they match again--@kristinashu will probably know what the proper order should be but I'm guessing that the wallet is meant to go with "affordability," the medal is meant to go with "creativity," etc.

![screen shot 2017-02-15 at 9 52 36 pm](https://cloud.githubusercontent.com/assets/1390212/23009727/6b03f0c0-f3cc-11e6-947d-99cf391ed21a.png)

CC @ScottDowne

**Comment by kristinashu** [comment]
Here's how they should be connected:
![screen-shot-2017-02-16-at-8 14 18-am](https://cloud.githubusercontent.com/assets/1068783/23029807/90816e82-f420-11e6-88d2-89556181a1a2.jpg)
