### ISSUE TITLE
A few minor text tweaks

### ISSUE THREAD

**Issue by mehan** [mozilla/nsf-challenge#53]
Just want to make the following minor tweaks for the sake of consistency:

![screen shot 2017-02-17 at 3 26 48 pm](https://cloud.githubusercontent.com/assets/1390212/23088404/f95f8a72-f530-11e6-9723-59f5afd5c608.png)

"Challenges" should start with a capital "C".

![screen shot 2017-02-17 at 3 26 54 pm](https://cloud.githubusercontent.com/assets/1390212/23088412/0581090c-f531-11e6-8cc7-18fabbc2c907.png)

The "S" in "started" should be lowercased.

![screen shot 2017-02-17 at 3 27 14 pm](https://cloud.githubusercontent.com/assets/1390212/23088418/1a146d6e-f531-11e6-9d2f-ec8ceb57497d.png)

This should be changed to read "Submissions open in June" (this might be a moot point, if this whole section goes away, with the removal of references to the email signup).

**Comment by ScottDowne** [comment]
Fixed.
