### ISSUE TITLE
Remove email sign-up

### ISSUE THREAD

**Issue by hannahkane** [mozilla/nsf-challenge#57]
(Moving tickets over from [non-code repo](https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/), since it seems like people are working here now)

We've decided not to offer the email sign-up, at least initially.

- Remove "Sign up for an email reminder" sentence from hero.
- Remove email signup CTA in pre-footer, and I guess center the remaining CTA? cc @kristinashu

**Comment by hannahkane** [comment]
From Kristina:

Two options:

Just centered it and put text onto one line.

<img width="1057" alt="screen shot 2017-02-17 at 3 31 16 pm" src="https://cloud.githubusercontent.com/assets/1068783/23087073/38894a7c-f526-11e6-8d69-6fd71fbca9b8.png">

Or put text and button onto one line, center them, and reduce purple background to about 140px in height.

<img width="1059" alt="screen shot 2017-02-17 at 3 37 10 pm" src="https://cloud.githubusercontent.com/assets/1068783/23087170/ff16d7cc-f526-11e6-94e8-ed582a7759fe.png">

I prefer the second option because it reduces the height slightly but understand that it's more work and _might_ be tricky to center (that was the case on the [science site](https://science.mozilla.org/) newsletter signup)?

<img width="1413" alt="screen shot 2017-02-17 at 3 40 24 pm" src="https://cloud.githubusercontent.com/assets/1068783/23087251/7e9153e2-f527-11e6-8d7a-2f0cd71510bb.png">

So up to you @ScottDowne!

**Comment by ScottDowne** [comment]
Fixed.
