### ISSUE TITLE
Link image credit to source

### ISSUE THREAD

**Issue by hannahkane** [mozilla/nsf-challenge#58]
The credit on the image we're using for the Raleigh event should link to the [source image](https://www.flickr.com/photos/bz3rk/7243110388/in/photolist-c33QnA-AUBT24-c33G5d-pAriiq-c33Gtq-pCs1jC-c33Ki7-pkZHtM-pkZfvj-pkYUUs-c33Gzm-c33J7u-2p9UiW-c33EA7-c33HXL-c33EdE-c33HNw-c33Fzo-c33Q5S-c33FFq-c33Jgd-c33Jph-fx8W1M-apyLRf-c33Ff3-c33Nfw-apw4Xa-apw2rr-apw46H-c33NFq-7tLsFL-c33Mnf-n3bDGZ-apyJpQ-apw5kR-7tLsPf-apyL5S-apw5KF-apw34V-apw4Ap-apyLvf-84KXKT-c33FrJ-apyKDb-apw2GT-c33GFE-apw2Uz-apyK3b-csmFUh-pCcMk8)

**Comment by hannahkane** [comment]
On second thought, let's just use this image: https://en.wikipedia.org/wiki/Raleigh,_North_Carolina#/media/File:Downtown-Raleigh-from-Western-Boulevard-Overpass-20081012.jpeg, since it's in the public domain.

**Comment by ScottDowne** [comment]
Closed https://github.com/mozilla/nsf-challenge/pull/64
