### ISSUE TITLE
Add cc license

### ISSUE THREAD

**Issue by hannahkane** [mozilla/nsf-challenge#59]
Legal requests the addition of this sentence to the site. @kristinashu - thoughts on how to best integrate this into the footer?

"This website is licensed under a [Creative Commons license](https://creativecommons.org/licenses/by-sa/3.0/deed.en), excluding portions of the content attributed to third parties."

**Comment by hannahkane** [comment]
From Kristina:

I guess stick it at the bottom...

<img width="1059" alt="screen shot 2017-02-17 at 3 37 10 pm" src="https://cloud.githubusercontent.com/assets/1068783/23087286/c9687814-f527-11e6-8aa8-9421aae7f127.png">

**Comment by kristinashu** [comment]
@hannahkane do we still need to add that line of text if we use the Raleigh image from wiki?

**Comment by hannahkane** [comment]
@kristinashu - yeah, I believe so, since it's clarifying that the site itself has a CC license.

**Comment by ScottDowne** [comment]
Fixed.

**Comment by kristinashu** [comment]
@hannahkane so we can't just have the CC icon and link to https://creativecommons.org/licenses/by-sa/3.0/deed.en

Like we have on https://mozilla.github.io/mofo-bootstrap/demo/
<img width="1367" alt="screen shot 2017-02-21 at 12 16 56 pm" src="https://cloud.githubusercontent.com/assets/1068783/23183089/b14ed0d8-f82f-11e6-9f2a-00084d9ed4d8.png">

Sorry, it's totally fine to have that text at the bottom if that's what legal needs, just double checking...
