### ISSUE TITLE
add links to event pages

### ISSUE THREAD

**Issue by hannahkane** [mozilla/nsf-challenge#60]
Pending final details and links from @mehan

**Comment by mehan** [comment]
@hannahkane @ScottDowne 

https://ti.to/mozilla-nsf-wins/raleigh
https://ti.to/mozilla-nsf-wins/oakland
https://ti.to/mozilla-nsf-wins/boulder
https://ti.to/mozilla-nsf-wins/nyc

Also one other minor change: the date on the page for the Oakland event needs to change to **April 9th**.

**Comment by mehan** [comment]
@ScottDowne Here are new links for the event registration forms.

Raleigh: https://docs.google.com/forms/d/e/1FAIpQLSd97uj6X64Yp0YyBsqgoJ9I72RStMeH6x_w36aS40PJYEcifQ/viewform

Oakland: https://docs.google.com/forms/d/e/1FAIpQLSe5UArgBjE_FohMl_2fyfIfygFDxuoWgxD1uyvrAedxErEVhA/viewform

Boulder: https://docs.google.com/forms/d/e/1FAIpQLScUKsFyozLBJQB4VIEwUQF4cMNlsae2cfkYtLblffyzy98ZMQ/viewform

NYC: https://docs.google.com/forms/d/e/1FAIpQLScILWp1JB-HpG16gX-mYXuo86a0d4ZED6MarVbmF9Zc50EdXw/viewform

**Comment by ScottDowne** [comment]
Updated in https://github.com/mozilla/nsf-challenge/commit/a2ca2c650da2e93affb05bc04c5bd738d45f251c
