### ISSUE TITLE
page width

### ISSUE THREAD

**Issue by hannahkane** [mozilla/nsf-challenge#61]
Migrating from non-code repo, since we seem to be working here now. See [original ticket](https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/issues/28) for more discussion.

From Kristina:

The page width on staging is wider than in the comps. The issue with this is that the sentences become difficult to read because there are too many words per line. 

Ideally, all the content is narrower. For example, making the body text the same width as the 4 event images on staging site.
<img width="1411" alt="screen shot 2017-02-06 at 10 24 52 am" src="https://cloud.githubusercontent.com/assets/1068783/22660479/89a18dda-ec56-11e6-9e74-1be763571e0d.png">

If that is problematic to do, then we could make the body text bigger (so there are fewer words per line).

**Comment by ScottDowne** [comment]
Fixed.
