### ISSUE TITLE
Design updates based on feedback

### ISSUE THREAD

**Issue by kristinashu** [mozilla/nsf-challenge#73]
Update current design based on [new copy](https://docs.google.com/document/d/1f6YdVzGJ2_uj9ZI2ImjOgMjFL16ROHT7bSReKfxpuJE/edit?usp=sharing)

Changes will include:
- remove event section
- add email signup
- additional tab section
- new graph
- new icons
- create 2 PDFs
- possibly add photos

cc @hannahkane

**Comment by kristinashu** [comment]
Timeline:
- copy should be finalized early next week
- I will finalize design by April 28
- @ScottDowne will start dev May 1
- launch May 5

**Comment by hannahkane** [comment]
@kristinashu - is the timeline/flowchart included in your list above? Just checking.

**Comment by kristinashu** [comment]
Still some polishing up to do but here is the initial comp with all the new updates: https://redpen.io/p/cx1e480fd9bb50a788

cc @jenntbeard @LindseyFrost @mehan

**Comment by hannahkane** [comment]
Looks great, @kristinashu! 

Are the pdf's on your list for Thursday?

**Comment by kristinashu** [comment]
Yes! Here is the first PDF https://drive.google.com/open?id=0B2irLVDJivhLc1psTnVBZWxoVjA
I think there will be some copy changes but this gives a general layout. If everyone is happy with this direction then I'll do the other.

I've also made a few updates based on redpen feedback from Jenn https://redpen.io/p/cx1e480fd9bb50a788

**Comment by hannahkane** [comment]
PDF looks good to me. :)

**Comment by kristinashu** [comment]
I believe I've done everything I can do for now (although I expect some copy edits):
- comp is here: https://redpen.io/zt134841c7aa9c7b27
- PDFs are [here](https://drive.google.com/open?id=0B2irLVDJivhLSU40QXJTSEJ2SE0)
- assets for dev https://drive.google.com/open?id=0B2irLVDJivhLUE1oLWlFVXpLRUU

**Comment by hannahkane** [comment]
Awesome! Thanks, @kristinashu. I've filed an implementation ticket, so I'm closing this one.

@jenntbeard - please file any add'l content updates as separate tickets. Thank you!

**Comment by jenntbeard** [comment]
Thank you!
