### ISSUE TITLE
Implement content and layout changes

### ISSUE THREAD

**Issue by hannahkane** [mozilla/nsf-challenge#74]
As discussed, we'll begin the implementation of the identified changes on Monday.

- comp is here: https://redpen.io/zt134841c7aa9c7b27
- PDFs are [here](https://drive.google.com/open?id=0B2irLVDJivhLSU40QXJTSEJ2SE0)
- assets for dev https://drive.google.com/open?id=0B2irLVDJivhLUE1oLWlFVXpLRUU
- copy is [here](https://docs.google.com/document/d/1f6YdVzGJ2_uj9ZI2ImjOgMjFL16ROHT7bSReKfxpuJE/edit)

**Comment by kristinashu** [comment]
Let me know if you have any questions about this. 

We has talked about possibly making this a multi page site but we should leave as a single page. It’s not so bad as is and there are too many legal/NSF constraints to change anything. You’ll just have to adjust the mobile version a little (reduce font size + line height and reduce padding). 

Copy doc has all the URLs you'll need.

**Comment by ScottDowne** [comment]
Staging is updated. https://wirelesschallenge.mofostaging.net/

All the content is updated, although some of the styling I didn't do yet if the previous styling still kinda worked.

I'm going to split it into content changes and style changes.

Updating content was a priority, and I figured styling could be done in another patch.

**Comment by hannahkane** [comment]
@ScottDowne - rad! I just took a quick look and everything seems great so far. Will do a more in-depth review later.

@jenntbeard - are you able to take a look today or Monday as well?

**Comment by jenntbeard** [comment]
Yes, taking a look now...

**Comment by kristinashu** [comment]
This is awesome Scott! I know you haven't focused on design yet, but I've added a screen cap of the staging site to redpen with some styling comments https://redpen.io/gyc6d2abde19648369
It would be great to get some of this finessing done before you tackle the 'bigger' design updates, just in case we run out of time. 

@jenntbeard, feel free to add any content comments to that redpen as well if that's easier.

We will need to update the PDFs, do you have the final copy from them? If so, I can update them now.

**Comment by jenntbeard** [comment]
This is awesome! I can't wait for @mehan to see it when he gets back on Monday. I will work on matching up the .pdf copy now @kristinashu in the original Gdoc (https://docs.google.com/document/d/1Ve4YazoUvF8kSogvqxTh5MmK59lxlNa8RARpM-SpfFo/edit).

**Comment by jenntbeard** [comment]
Okay, all done with the .pdf reconciliation process. Thanks team!!

**Comment by kristinashu** [comment]
Updated pdfs are here: https://drive.google.com/open?id=0B2irLVDJivhLZ2pTX2ZLUmtlS1E 

If they look good to Mehan, then Scott can update the site. I'll be on PTO Monday but if they need any changes I will do them first thing Tues.

**Comment by mehan** [comment]
@kristinashu @jenntbeard These look great! Really love the design and find them very easy to read and scan for information.

The only thing that stuck out to me is that there are some inconsistencies in the timeline on the second page of each PDF. It looks like the milestone for "Stage 1 prizes announced" should be January 2018, not January 2017. That would then push some of the later milestones into 2019. Not sure if you guys have agreed on an adjusted timeline with the NSF (if so, apologies, I'm only starting to get caught up from the last two weeks!) but my understanding was that this whole thing needed to be a wrap before the end of 2018. I think our original timeline had Stage 2 submissions being due in June 2018, with the announcement and awards ceremony to follow that same summer/fall.

**Comment by jenntbeard** [comment]
Hmm, no updates with NSF on timeline that I'm aware of - the dates for that timeline image should match the dates in the content master doc - https://docs.google.com/document/d/1f6YdVzGJ2_uj9ZI2ImjOgMjFL16ROHT7bSReKfxpuJE/edit#. Thanks in advance for updating @kristinashu. Thanks all!

**Comment by kristinashu** [comment]
Sorry for the typo, I've updated Jan 2017 to Jan 2018.

@ScottDowne please update the two PDFs with [these updated versions](https://drive.google.com/open?id=0B2irLVDJivhLZ2pTX2ZLUmtlS1E
). And the timeline images on the site to:


<img width="783" alt="nsf-timeline-desktop" src="https://cloud.githubusercontent.com/assets/1068783/25858006/83364036-348f-11e7-8821-82c29a4e5b25.png">
<img width="305" alt="nsf-timeline-mobile" src="https://cloud.githubusercontent.com/assets/1068783/25858007/833b6b06-348f-11e7-9eaa-e85c09d1bf90.png">

**Comment by jenntbeard** [comment]
@kristinashu These dates still don't match the master. The last three milestones should be June 2018, August 2018, and Summer 2018 (which is correct). Thanks!

The dates come from this copy (for reference):
Stage 1 Design Concepts submissions will be accepted from June 15, 2017 through November 15, 2017. Prizes and entrants eligible to compete in Stage 2 will be announced in January 2018.
Stage 2 Working Prototype submissions will be accepted from January 15, 2018 through June 15, 2018.  Prizes will be announced in August 2018. Finalists during the Working Prototype Stage may be required to provide live demos for judges and/or a public audience at a Challenges Showcase in Summer 2018.

**Comment by kristinashu** [comment]
Ok updated, please [check them again](https://drive.google.com/open?id=0B2irLVDJivhLZ2pTX2ZLUmtlS1E
) 🤞 

<img width="783" alt="nsf-timeline-desktop" src="https://cloud.githubusercontent.com/assets/1068783/25859400/490992b0-3493-11e7-9ea6-0a175e6c4860.png">
<img width="305" alt="nsf-timeline-mobile" src="https://cloud.githubusercontent.com/assets/1068783/25859401/4921770e-3493-11e7-99a0-9569f5165fe8.png">

**Comment by jenntbeard** [comment]
Looks great to me, thanks!

**Comment by ScottDowne** [comment]
Should be updated on staging now: https://wirelesschallenge.mofostaging.net/

**Comment by mehan** [comment]
@kristinashu @ScottDowne Looks great on the PDFs, though I'm still seeing the incorrect dates on the timeline on the site itself. Not sure if this is just a local caching issue?

![screen shot 2017-05-10 at may 10 2 33 22 pm](https://cloud.githubusercontent.com/assets/1390212/25922348/beb4eece-358d-11e7-8795-83dd75ae2e1b.png)

**Comment by mehan** [comment]
@kristinashu @ScottDowne Just noticed one other minor issue with the PDF for Challenge #2--it still says "call to action" on the first page, which looks like it's a placeholder:

![screen shot 2017-05-12 at 2 08 12 pm](https://cloud.githubusercontent.com/assets/1390212/26017070/9277fadc-371c-11e7-88ec-ab491b9c7d89.png)

**Comment by kristinashu** [comment]
Ok, I've updated the PDF to just "How to get involved"

@ScottDowne I think I updated it here ok https://github.com/mozilla/nsf-challenge/tree/master/source/assets

**Comment by ScottDowne** [comment]
Updated staging, if it all looks good, I can move it to prod. https://wirelesschallenge.mofostaging.net/

**Comment by mehan** [comment]
@ScottDowne The last thing I'm seeing is that the timeline on the page still looks incorrect. It should be this one, which Kristina updated earlier:

![timeline](https://cloud.githubusercontent.com/assets/1068783/25859400/490992b0-3493-11e7-9ea6-0a175e6c4860.png)

**Comment by ScottDowne** [comment]
I thought she already updated it? Let me take a closer look.

**Comment by kristinashu** [comment]
I only updated the pdf. I didn't update the image within the site. You will both images in https://github.com/mozilla/nsf-challenge/issues/74#issuecomment-300206555

**Comment by ScottDowne** [comment]
Yeah, see that now, updating.

**Comment by ScottDowne** [comment]
OK, now try: https://wirelesschallenge.mofostaging.net/

**Comment by mehan** [comment]
@ScottDowne Looks great! All set for launch, as far as I'm concerned. 👍🏽

**Comment by hannahkane** [comment]
🚀 🚀 🚀

**Comment by mehan** [comment]
Looks like the site is live! Thanks so much, @ScottDowne @kristinashu @hannahkane @jenntbeard and @mmmavis! Really appreciate all of your hard work on this site over the last few months. Thrilled with the result and to finally ship!

**Comment by hannahkane** [comment]
Just FYI, the DNS settings were set today, and it can take up to 24 hours to propagate across the internet (meaning not everyone can necessarily see the content).

Apologies for not flagging this earlier.

**Comment by mehan** [comment]
@hannahkane Ah okay, no worries--given that it's late in the day, we're probably not going to do much promotion around this until tomorrow anyway. Thanks!
