### ISSUE TITLE
Copy changes

### ISSUE THREAD

**Issue by hannahkane** [mozilla/nsf-challenge#75]
From @jenntbeard:

A few copy edits emerged from our back and forth w/NSF. They can be viewed through the tracked changes in this doc - https://docs.google.com/document/d/1f6YdVzGJ2_uj9ZI2ImjOgMjFL16ROHT7bSReKfxpuJE/edit#. Or, I have highlighted the individual changes below by section. Thanks!

Challenges Tab: 
- Challenge 1 question statement is now - "How can we leverage wireless technology to keep people connected to each other and to vital information sources in the aftermath of a disaster where Internet access is unavailable or compromised?" (Previously was - "How can we leverage wireless technology to keep people connected to each other and to vital information sources in the aftermath of a disaster?")
- Challenge 2 question statement is now - "How can we leverage existing infrastructure to provide robust wireless Internet connectivity in communities that need greater access?" (Previously was - "How can we leverage existing infrastructure to provide reliable wireless Internet connectivity in communities that need greater access?") 

Submit Tab:
- Judging criteria - two labels are changing. 'Creativity' should now be 'Differentiation' and 'Adaptability' should now be 'Scalability'. 

cc: @mehan

**Comment by hannahkane** [comment]
@kristinashu - do you think we can use the same icons for the Judging criteria, given the label changes?

**Comment by kristinashu** [comment]
I've updated the copy and the "scalability" icon (adaptability still works) https://redpen.io/zt134841c7aa9c7b27

**Comment by hannahkane** [comment]
@ScottDowne - seems like you did this, so closing
