### ISSUE TITLE
Remove one judging criteria from WINS site

### ISSUE THREAD

**Issue by jenntbeard** [mozilla/nsf-challenge#76]
Hi - we would like to remove the last judging criteria, labeled "New Work" (see below) from the site. (We have one more minor change (likely an added sentence to one of the FAQs) coming after the last bit of back and forth with NSF winds down.) :) Thanks!

REMOVE:
New Work:  Does the proposed solution consist of pre-existing technology already developed by the submitter, or will the Challenge provide an opportunity for further development and refinement?

**Comment by hannahkane** [comment]
@ScottDowne - seems like did this one as well, so closing
