### ISSUE TITLE
Timeline and Stage 1/2 containers collapse on mobile

### ISSUE THREAD

**Issue by mehan** [mozilla/nsf-challenge#84]
Screenshot was taken in Chrome for iOS. CC @ScottDowne 

![img_5485](https://cloud.githubusercontent.com/assets/1390212/26132228/b376ff1e-3a53-11e7-8210-dee09d91cda8.PNG)

**Comment by ScottDowne** [comment]
Fixing. It's actually also on Safari. Which chrome on iOS is actually just Safari.

**Comment by ScottDowne** [comment]
Pushing up a fix now.

**Comment by ScottDowne** [comment]
Should be live now.
