### ISSUE TITLE
Site description is "TODO" on social

### ISSUE THREAD

**Issue by mehan** [mozilla/nsf-challenge#86]
Here's what it looks like when shared via Slack; I've been told it displays the same way in Facebook as well:

![screen shot 2017-05-17 at may 17 8 45 41 am](https://cloud.githubusercontent.com/assets/1390212/26163291/13d71814-3ade-11e7-9e33-7c11c5dfeecc.png)

**Comment by ScottDowne** [comment]
Do we have copy for that? I can insert it once I have it.

**Comment by ScottDowne** [comment]
We just need to make updates to here: https://github.com/mozilla/nsf-challenge/blob/master/source/pug/partials/header.pug#L9-L14
