### ISSUE TITLE
New content for 6/15

### ISSUE THREAD

**Issue by mehan** [mozilla/nsf-challenge#90]
Hey @hannahkane @ScottDowne,

Not sure how much you guys discussed this with @jenntbeard but we're going to need to have a few minor things added to the site when the application cycle opens on 6/15. Here's what we need to add:

- Rules & Regulations: Scott already created a page for these, which pulls from a markdown file; once I have the language finalized, I can add and format it and send a pull request.
- Link to application form: Due to delays with Fluxx, we're going to use Google Forms for the first round of the application, so we'll need to link to the external form.
- Application guidance PDF: We're going to provide all of the application questions in advance to help applicants prepare, probably as a PDF.

One thought is that we could repurpose the "Submissions will be accepted..." bit below to link to the PDF? And then the button could link to the Google Form?

![screen shot 2017-05-24 at may 24 11 53 36 am](https://cloud.githubusercontent.com/assets/1390212/26420536/b2bab596-4077-11e7-8303-bf0ef1ee561a.png)

Let me know what you guys think when you get a chance. Thanks!

**Comment by ScottDowne** [comment]
This all seems super easy from a dev point of view. Just let me know when the links/pull request/pdf is ready, and I can make these changes/merge any pull requests.

**Comment by mehan** [comment]
Great, thanks @ScottDowne! Let me know if there's a date you guys want everything by in order to have the changes ready by 6/15 and I will make sure we get everything to you by then.

**Comment by ScottDowne** [comment]
My guess is just have it done a few days lead time before you want it shipped, and we should be good. That said, sooner is always better ;).

**Comment by mehan** [comment]
Cool, I will set 6/12 as the drop-dead date for having everything finalized but will definitely aim to get it to you sooner. Thanks!

**Comment by kristinashu** [comment]
Mehan's suggestion to repurpose the "Submissions will be accepted..." bit below to link to the PDF and then the button could link to the Google Form sounds good to me. Just add a yellow underline to the PDF link.

**Comment by mehan** [comment]
Hi @ScottDowne and @hannahkane,

Here is most of the content that we'll want to have added to the site for the 6/15 update:

- The [Intent to Apply Form](https://goo.gl/forms/19P9QlkLZ93NzgG13) 
- The [Application guide PDF](https://github.com/mozilla/nsf-challenge/files/1069993/NSFWINSapplicationguide.pdf)

The text in the below screenshot should read "[Download the application guide] and begin your application now" and the button should read "Intent to Apply Form". Could we also add a button to the top nav that says "Apply Now" and which links down to this section?

![screenshot](https://cloud.githubusercontent.com/assets/1390212/26420536/b2bab596-4077-11e7-8303-bf0ef1ee561a.png)

The last bit that we'll need is the rules & regulations. Unfortunately, this has gotten held up again due to legal issues. I am doing my best to resolve those and hope to add the final rules & regs and submit a PR before the 15th. If nothing else, I will update the placeholder text for that page before the 15th, if we're not able to finalize the rules & regs by then. There's also a chance that some of the content in the Application Guide will change based on the rules & regs (I will let you know if this is the case).

Thanks and let me know if you have any questions on this!

**Comment by hannahkane** [comment]
Thanks, @mehan.

@ScottDowne - assigning to you and putting in the milestone that ends this Friday, for consistency with other projects, though the due date is earlier.

**Comment by ScottDowne** [comment]
@hannahkane just a status update. Main dev parts are done and on staging. We still need to figure out what the rules and regulations page, but it's all copy and going through legal and such process.

After chatting with @mehan about the dev parts, we decided to hold off putting this on prod until the day of, if possible, and keeping it on staging for now. I don't see much risk in that.

**Comment by mehan** [comment]
Thanks, @ScottDowne! I'm working to finalize the rules & regs now and will aim to get you a PR by tomorrow at latest. Just a heads-up that a few things will be changing in the PDF as well, so we'll need to swap out that file for a newer version.

**Comment by mehan** [comment]
Hey @ScottDowne @hannahkane,

I've got the final changes to the site for the 6/15 update ready:

- All the final rules & regulations language is in #94 
- Here is the final version of the [Application Guide](https://github.com/mozilla/nsf-challenge/files/1076137/NSFWINSapplicationguide.pdf), which should replace the previous version (the latest version says v1.1 on the first page)

Once these changes have been made, this should be ready to go to production any time tomorrow. 

Let me know if you have any questions and many thanks!

**Comment by hannahkane** [comment]
This is all on production now, right? Can we close this?

**Comment by mehan** [comment]
@hannahkane yep, i believe so--gonna go ahead and close.
