### ISSUE TITLE
Social graphics

### ISSUE THREAD

**Issue by hannahkane** [mozilla/nsf-challenge#91]
## Specs

We need social graphics to promote the call for submissions.
- [ ] 627x627
- [ ] 1024x512 (Twitter)
- [ ] 1200x717 (Facebook)

## Content
Use NSF logo and "powered by Mozilla" convention
Use full name of program: "Wireless Innovation for a Networked Society Challenges"
Submit by October 15
https://wirelesschallenge.mozilla.org

(@jenntbeard, can you please advise on the above? Given the length of the title, I'm not sure we need a tagline as well, though it might be good to mention the prize money. What do you think?)

## Look and Feel
- look to @flukeout's work on the [Gigabit social](https://drive.google.com/drive/folders/0B_CPRh4f3yyqTHJDT0NSZjdBY00) for inspiration
- align with [NSF WINS branding](https://wirelesschallenge.mozilla.org)

**Comment by hannahkane** [comment]
@jenntbeard - can you also include information about your promotional plan, please - when do you need these by? thanks!

**Comment by jenntbeard** [comment]
Hi, thanks! Yes, we are starting to promote now, but the letter of intent process will open on June 15, so having them on or around then would be ideal. I think adding "$2 million in prizes" would be an okay tagline - sound good to you @mehan? 

Using a version of [this image](https://drive.google.com/open?id=0B1Tu07mQk89LX3Q0R1QzLU1JbVk) would be great - maybe extending the purple for white text overlay?

**Comment by hannahkane** [comment]
cc @xmatthewx - anyone in mind to work on this early next week?

**Comment by xmatthewx** [comment]
@flukeout - do you have time this week or early next week for some social graphics?

**Comment by flukeout** [comment]
Working on it now.

**Comment by flukeout** [comment]
Okay, here's the ``1200x717`` version. Please provide feedback on this, and I'll create the other two sizes. Thanks and sorry for the delay!

![nsf-challenge-1200x717](https://user-images.githubusercontent.com/25212/28036433-15a3e29e-656d-11e7-98a2-1af221d18a2d.png)

cc @jenntbeard @mehan

**Comment by mehan** [comment]
@flukeout Looks great--thanks!

**Comment by jenntbeard** [comment]
No worries, this looks perfect to me except that Challenge needs an 's' to emphasize that there are two of them. NSF will love their logo on it. Anything else, @Mehan? Thanks, @flukeout!

**Comment by mehan** [comment]
@jenntbeard Ah, good catch Jenn!

**Comment by flukeout** [comment]
@jenntbeard @mehan I made the other two sizes and put the banners and working files into [this folder on the drive](https://drive.google.com/drive/folders/0B_CPRh4f3yyqcnBnbXZfbTRLNGM?usp=sharing). Let me know if you need any changes or have trouble accessing anything.

Otherwise, let me know all is good and we can close this issue. Cheers.

**Comment by jenntbeard** [comment]
Awesome sauce, thank you so much!!

**Comment by mehan** [comment]
These all look great, many thanks, @flukeout!

**Comment by flukeout** [comment]
No probs, closing!

**Comment by flukeout** [comment]
@jenntbeard @mehan Just a heads up that there was a typo in the ``1024x512`` banner in case you've already downloaded them. I've updated the banners in the folder.

**Comment by mehan** [comment]
Thanks for the heads-up, @flukeout! Appreciate it.
