### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by hannahkane** [mozilla/nsf-challenge#97]
Hey @gvn and @mmmavis - I know neither of you has been working on this site, but it's more related to the Network than Advocacy work, so I'm wondering if we can start transferring ownership from @ScottDowne to you two. It requires little maintenance at this point, though there will be some content changes in the future.

Right now we need to add analytics to the site so we can be capturing some metrics to use in reports to funders. Is this something one of you could do before the end of next week?

cc @alanmoo

**Comment by gvn** [comment]
Sure, are we just adding stock GA? 

I believe we'll need embed code from @vojtechmzl

**Comment by vojtechsedlak** [comment]
Here is a standard container for a new GA property I just created. Let me know once it's added to the site and I can test that data is coming through. Thanks!
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-87658599-13', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by alanmoo** [comment]
Don't forget do not track code. I believe @cadecairos has a gist up for that wrapper.

-Alan Mooiman,
Mozilla Foundation Engineering Manager
Eastern Daylight Time (USA) UTC-4

**Comment by mehan** [comment]
Hey @ScottDowne, @gvn and @mmmavis--what's the status on having GA added to this site?

**Comment by ScottDowne** [comment]
I talked with Hannah, and I think I can do this today.

**Comment by ScottDowne** [comment]
Pull request is here: https://github.com/mozilla/nsf-challenge/pull/98

@alanmoo @vojtechmzl

**Comment by alanmoo** [comment]
Closed by #98

**Comment by ScottDowne** [comment]
@vojtechmzl this has finally landed and is now live on production. Mind giving it a quick QA when you get a chance?

https://wirelesschallenge.mozilla.org/

**Comment by vojtechsedlak** [comment]
Thanks @ScottDowne, data is flowing into GA and I tested the Do Not Track setup as well. All good here.

**Comment by mehan** [comment]
Great, many thanks for helping get this set up, all!
