### ISSUE TITLE
Update application guide PDF

### ISSUE THREAD

**Issue by mehan** [mozilla/nsf-challenge#99]
Hello @hannahkane! We've got a new version of our application guide that we'd love to have updated on the site. Here's the latest version of the PDF: [NSF WINS application guide.pdf](https://github.com/mozilla/nsf-challenge/files/1349625/NSF.WINS.application.guide.pdf)

Currently, the PDF is linked to [in the "Apply" section of the site.](https://wirelesschallenge.mozilla.org/#Apply) Thanks!

**Comment by hannahkane** [comment]
@gvn - wondering if you have a few moments to make this update to the NSF WINS Challenge website?

**Comment by gvn** [comment]
Sure I can take this

**Comment by mehan** [comment]
@gvn @hannahkane Any update on when this will be live on production? Thanks!

**Comment by gvn** [comment]
@ScottDowne This patch is landed. Are you able to deploy the site?

**Comment by gvn** [comment]
@mehan Should be deployed to prod now. Can you verify?

**Comment by mehan** [comment]
@gvn Yep, looks good. Thanks, all!
